sonar.projectKey=portfolio-tracker
sonar.projectName=DevOps Portfolio Tracker
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.exclusions=**/config/**,**/entity/**

sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=target/jacoco.exec

sonar.login=${SONAR_TOKEN}
sonar.host.url=${SONAR_HOST_URL}
